#!/bin/sh

# This target ships a native netifd configuration using `device` and bridge
# `ports`.  LuCI's generic compatibility dialog for pre-21.02 `ifname`
# configurations is not applicable here and can be falsely triggered by stale
# browser-side UCI state after a network restart.
interfaces_js=/www/luci-static/resources/view/network/interfaces.js

[ -f "$interfaces_js" ] || exit 0

sed -i \
	-e '/render:function(data){if(this\.interfaceBridgeWithIfnameSections()\.length)$/s/if(this\.interfaceBridgeWithIfnameSections()\.length)$//' \
	-e '/return this\.renderBridgeMigration();else if(this\.deviceWithIfnameSections()\.length||this\.interfaceWithIfnameSections()\.length)/d' \
	-e '/return this\.renderIfnameMigration();var dslModemType=/s/^return this\.renderIfnameMigration();//' \
	"$interfaces_js"

rm -f /tmp/luci-indexcache
rm -rf /tmp/luci-modulecache

exit 0
