#!/bin/sh /etc/rc.common

START=96
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/be6500-qos-watch
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 0
	procd_set_param stderr 0
	procd_close_instance
}

reload_service() {
	/usr/sbin/be6500-qos-apply >/dev/null 2>&1
}

service_triggers() {
	procd_add_reload_trigger be6500_oem device_manager network firewall ecm
}
