#!/bin/sh /etc/rc.common

START=96
USE_PROCD=1

start_service() {
	/usr/sbin/be6500-qos-apply >/dev/null 2>&1
}

reload_service() {
	/usr/sbin/be6500-qos-apply >/dev/null 2>&1
}

service_triggers() {
	procd_add_reload_trigger be6500_oem network firewall
}
