#!/bin/sh /etc/rc.common

START=96
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/libexec/be6500-led-control run
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

reload_service() {
	/usr/libexec/be6500-led-control apply
}

stop_service() {
	/usr/libexec/be6500-led-control clear
}
