#!/bin/sh /etc/rc.common

START=22
USE_PROCD=1

start_service() {
	/usr/libexec/be6500-fw4-multiwan
}

stop_service() {
	/usr/libexec/be6500-fw4-multiwan clear
}

reload_service() {
	/usr/libexec/be6500-fw4-multiwan
}
